// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ukbeldtxeeuxbadepfta.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVrYmVsZHR4ZWV1eGJhZGVwZnRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwOTg4NDYsImV4cCI6MjA3MzY3NDg0Nn0.0RF2KnnDO8ZZromCzFz6Fk45gQMWaivGcCsGG5_AB6o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});